FROM golang:alpine as build-env

RUN apk add build-base linux-headers
RUN apk --update add ca-certificates

RUN mkdir /external-initiator
WORKDIR /external-initiator
COPY go.mod go.sum ./
RUN go mod download

EXPOSE 8080

RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -directory="./" --command="./external-initiator"

