#!/bin/bash

set -e

source ./integration/common

source_mock_env

run_test() {
  trap exit_handler EXIT

  mkdir -p "$LOG_PATH"

  title "Initiating a fresh test"

  # Remove old volumes so we can run a fresh test
  reset

  start_docker

  add_ei

  # Run EI after access credentials has been generated
  run_ei

  login_chainlink

  # Address based
  ./integration/test_ei_event "eth-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "eth-mock-ws" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "hmy-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "hmy-mock-ws" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "xtz-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "ont-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "bsc-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "bsc-mock-ws" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "iotx-mock-grpc" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "cfx-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "cfx-mock-ws" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "keeper-mock-http" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "keeper-mock-ws" "$EVM_SUBSCRIBED_ADDRESS" "" 1
  ./integration/test_ei_event "birita-mock-http" "$BIRITA_PROVIDER_ADDRESS" "" 1

  # Account based
  ./integration/test_ei_event "near-mock-http" "" "$NEAR_ORACLE_ACCOUNT_ID" 3
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_1_ACCOUNT_ID" 1
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_2_ACCOUNT_ID" 1
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_3_ACCOUNT_ID" 1

  stop_docker

  title "Done running tests"
}

run_test
