#!/bin/bash

set -e

source ./integration/common

run_test() {
  trap exit_handler EXIT

  mkdir -p "$LOG_PATH"

  title "Initiating a fresh test"

  # Remove old volumes so we can run a fresh test
  reset

  start_docker

  add_ei

  # Run EI after access credentials has been generated
  run_ei

  login_chainlink

  ./integration/test_ei_event "eth-mock-http" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "eth-mock-ws" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "hmy-mock-http" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "hmy-mock-ws" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "xtz-mock-http" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "ont-mock-http" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "bsc-mock-http" "$SUBSCRIBED_ADDRESS" ""
  ./integration/test_ei_event "bsc-mock-ws" "$SUBSCRIBED_ADDRESS" ""
  # ./integration/test_ei_event "near-mock-http"

  source ./integration/test_substrate.env
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_1_ACCOUNT_ID"
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_2_ACCOUNT_ID"
  ./integration/test_ei_event "substrate-mock-ws" "" "$SUBSTRATE_OPERATOR_3_ACCOUNT_ID"

  stop_docker

  title "Done running tests"
}

run_test
