#!/bin/bash

source ./integration/common

run_setup() {
  mkdir -p "$LOG_PATH"

  title "Setting up test environment"

  pushd integration-scripts >/dev/null || exit
  local log=$LOG_PATH/integration_setup.log
  yarn install
  yarn setup | tee "$log"
  popd >/dev/null || exit

  build_docker

  title "Done setting up test environment"
}

run_setup
