#!/bin/bash

set -e

source ./integration/common

source_mock_env

title "EI event test using $1"

event_test() {
  trap exit_handler EXIT

  expected_job_count=$(expr "$(docker exec integration_chainlink chainlink -j jobs list | jq length)" + 1)
  local log=$LOG_PATH/send_event_transaction.log

  pushd integration/scripts >/dev/null || exit
  yarn create-job "$1" "$2" "$3" | tee "$log"
  popd >/dev/null || exit

  jid=$(grep <"$log" "Deployed Job" | awk '{print$4}')

  # Check job counts
  assert "Jobs count" "docker exec integration_chainlink chainlink -j jobs list | jq length" "$expected_job_count"

  # Check job runs
  assert "This job Runs count" "docker exec integration_chainlink chainlink -j runs list --jobid $jid | jq length" 1

  # Check that the run completed
  assert "Run completed" 'docker exec integration_chainlink chainlink -j runs list --jobid $jid | jq ".[].status" | sed s/\"//g' completed
}

event_test "$1" "$2" "$3"
